---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/transmission/config/sonarr-config:/config
      - /mnt/transmission/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/transmission/config/radarr-config:/config
      - /mnt/transmission/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/transmission/config/lidarr-config:/config
      - /mnt/transmission/data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/transmission/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1013
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/transmission/config/bazarr-config:/config
      - /mnt/transmission/data/media/movies:/data:/movies #optional
      - /mnt/transmission/data/media/tv:/data:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

