---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /servarr/config/sonarr-config:/config
      - servarr/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /servarr/config/radarr-config:/config
      - servarr/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /servarr/config/lidarr-config:/config
      - servarr/data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /servarr/config/overseerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /servarr/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=13010
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=claim-R84dZi19xy3Qz1k9pVqg
    volumes:
      - /servarr/config/plex-config:/config
      - servarr/data/media:/media
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=13014
      - PGID=13000
      - TZ=America/Sao_Paulo
    volumes:
      - /servarr/config/tautulli-config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=13013
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - /servarr/config/bazarr-config:/config
      - servarr/data/media/movies:/movies
      - servarr/data/media/tv:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
    volumes:
      -  /servarr/config/qbittorrent-config:/config
      -  servarr/data/torrents:/data/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped